license="${mod_license}"
issueTrackerURL="https://github.com/eretenkodaniil16-rgb/mkm-rpg/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/eretenkodaniil16-rgb/mkm-rpg"
authors="eretenkodaniil16-rgb"
description='''
MKM is a large-scale RPG conversion for Minecraft focused on deep character progression,
active abilities, CRPG-style quests and dialogue, factions, exploration, encounters and bosses.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
